{
    "exception": {
        "internalServerError": "Um erro inesperado ocorreu."
    }
}